[build]
  [context.deploy-preview]
    ignore = "if [[ $HEAD == *feature/* ]]; then exit 1; else exit 0; fi"

[[redirects]]
  from = "/swap#/swap"
  to = "/swap"
  status = 301
  force = true
  query = { outputCurrency = ":outputCurrency", inputCurrency = ":inputCurrency" }